FROM python:3.11-slim

# Install k6
RUN apt-get update && apt-get install -y gnupg curl

RUN curl -s https://dl.k6.io/key.gpg | apt-key add -

RUN echo "deb https://dl.k6.io/deb stable main" \
    > /etc/apt/sources.list.d/k6.list

RUN apt-get update && apt-get install -y k6

WORKDIR /app

COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

COPY . .

CMD ["python", "app.py"]
